apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/supersite.localhost/wp_data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/supersite.localhost/db_data"

