apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: alpine
    image: reg.ntl.nc/proxy/library/alpine:latest
    command: ["sleep", "3600"]
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: username.txt
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: password.txt
  restartPolicy: Never

