apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 5
  source:
    repoURL: https://github.com/AndreGirbal/VagrantLab.git
    path: helms/grafana
    targetRevision: HEAD
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true